package tech.dojo.pay.sdk.card

import android.content.Intent
import android.os.Bundle
import androidx.activity.viewModels
import androidx.appcompat.app.AppCompatActivity
import tech.dojo.pay.sdk.R
import tech.dojo.pay.sdk.card.entities.DojoCardPaymentResult

internal class DojoCardPaymentActivity : AppCompatActivity() {

    private val viewModel: DojoCardPaymentViewModel by viewModels {
        DojoCardPaymentViewModelFactory(intent.extras)
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_dojo_card_payment)
        observeEvents()
    }

    private fun observeEvents() {
        viewModel.events.observe(this) { event ->
            when (event) {
                is DojoCardPaymentEvent.ReturnResult -> returnResult(event.result)
                is DojoCardPaymentEvent.Navigate3DS -> navigate3DS()
            }
        }
    }

    private fun returnResult(result: DojoCardPaymentResult) {
        val data = Intent()
        data.putExtra(DojoCardPaymentResultContract.KEY_RESULT, result)
        setResult(RESULT_OK, data)
        finish()
    }

    private fun navigate3DS() {
        val fragment = Dojo3DSFragment().apply {
            arguments = Bundle().apply {
                putString(
                    Dojo3DSFragment.KEY_STEP_UP_URL,
                    "https://centinelapistag.cardinalcommerce.com/V2/Cruise/StepUp"
                )
                putString(Dojo3DSFragment.KEY_MD, "6494313045486780204006")
                putString(
                    Dojo3DSFragment.KEY_JWT,
                    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI3ZTBlZmY3Yy1lNDFlLTQ4NWItYTFhYS1hZTgzYjM5ZGMzYzUiLCJpYXQiOjE2NDk0MzEzMDQsImlzcyI6IjVkZDgzYmYwMGU0MjNkMTQ5OGRjYmFjYSIsImV4cCI6MTY0OTQzNDkwNCwiT3JnVW5pdElkIjoiNWZlMzc3Y2UwOWM1MGIyZDQwOGY2Y2YwIiwiUGF5bG9hZCI6eyJBQ1NVcmwiOiJodHRwczovL21lcmNoYW50YWNzc3RhZy5jYXJkaW5hbGNvbW1lcmNlLmNvbS9NZXJjaGFudEFDU1dlYi9wYXJlcS5qc3A_dmFhPWImZ29sZD1BQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUEiLCJQYXlsb2FkIjoiZU5wVlVkdFN3akFRZmM5WE1EamptMDJidHR4Y01nT2k0NDNMS0k3QVcyMFgyckZwUzlvSyt2VW1wWUMrN1RtN201eHpGdWFoUkJ5OW9sOUs1RERHUFBjMjJJaUNmck03WEhhV0lkdEU2M0QwdVg2MzhxZXAyZVF3Rzd6Z2xzTVh5anhLRTI0WnBzR0FIaUZSVDBnLzlKS0NnK2R2aHc4VDdwaHV5MjBEclNFQmdmSmh4QzFtTzI0TDZBRVJTRHlCUENzLzRzaS9DbENrUUN1R2dKK1dTU0cvZWNjeGdSNEJnVkxHUEN5S3JFZnBicmN6Y08rSkxFYkRUd1ZRM1NOQXoxSm1wYTV5NVhBZkJYejY5cmlhM3NYcFdBVFpTb1MzSGxzdHhvdko4L3huMEFlcUp3Z0VYb0djbVl5Wmp0bHBXRzZQV1QzSEFWcnhCRHloaGZETEM2dGxYNnNNbExTYUlwRHB6d1lIWk9uT1gwTDVLYVhFeEZlR21MSi9RZ1J3bjZVSnFobVY1NmxXTnM3aWIrNTFxbjZoQW5QdGJwc3hXOGRhNFdvOVVza3d4enJzUjFWTVZPL1ErbWkwdnErcS90MzlGMlE4cDRjPSIsIlRyYW5zYWN0aW9uSWQiOiI5Qlk4WWgyZ2lmaERrZlcxc0tPMCJ9LCJPYmplY3RpZnlQYXlsb2FkIjp0cnVlLCJSZXR1cm5VcmwiOiJodHRwczovL3dlYi5lLnRlc3QuY29ubmVjdC5wYXltZW50c2Vuc2UuY2xvdWQvcGF5bWVudHMvMTJ6Y3ZIdWE3cnRrYkhHcWo4elRzX3J5N1dRSW1kcnRhTWVkSVNKTFA4UlFTb1RiY3Vsdm5IUmMyRGtqa2Q4dkdhbjFhQWhkVm5nY1JSY3lQN1lmSmtqdjNLdzlIWG93bHhTeFdXU2JtQTFTbmpZenEtNG13aG53Z3FMcU4tUmdMcUpUek9nczh0ZGdia2NOUkVwSUlpQmczRDVmL1RocmVlRFNlY3VyZTIwQ29tcGxldGUifQ.dSTP8M-hHgZFynELDMHAPSPjdUTpceTKlTjxUo5G7g4"
                )
            }
        }
        supportFragmentManager
            .beginTransaction()
            .add(R.id.container, fragment)
            .commit()
    }

    override fun onBackPressed() {
        if (viewModel.canExit) super.onBackPressed()
    }
}