package tech.dojo.pay.sdk.card

import android.content.Intent
import android.os.Bundle
import androidx.activity.viewModels
import androidx.appcompat.app.AppCompatActivity
import tech.dojo.pay.sdk.R
import tech.dojo.pay.sdk.card.entities.DojoCardPaymentResult

internal class DojoCardPaymentActivity : AppCompatActivity() {

    private val viewModel: DojoCardPaymentViewModel by viewModels {
        DojoCardPaymentViewModelFactory(intent.extras)
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_dojo_card_payment)
        observeEvents()
    }

    private fun observeEvents() {
        viewModel.events.observe(this) { event ->
            when (event) {
                is DojoCardPaymentEvent.ReturnResult -> returnResult(event.result)
                is DojoCardPaymentEvent.Navigate3DS -> navigate3DS()
            }
        }
    }

    private fun returnResult(result: DojoCardPaymentResult) {
        val data = Intent()
        data.putExtra(DojoCardPaymentResultContract.KEY_RESULT, result)
        setResult(RESULT_OK, data)
        finish()
    }

    private fun navigate3DS() {
        val fragment = Dojo3DSFragment().apply {
            arguments = Bundle().apply {
                putString(
                    Dojo3DSFragment.KEY_STEP_UP_URL,
                    "https://centinelapistag.cardinalcommerce.com/V2/Cruise/StepUp"
                )
                putString(Dojo3DSFragment.KEY_MD, "6494296322846713204006")
                putString(
                    Dojo3DSFragment.KEY_JWT,
                    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIzYWFhY2Y4Yi0zZTgwLTQ1YWItYmI4ZC0xMWU4MTQ2MGMwMjYiLCJpYXQiOjE2NDk0Mjk2MzIsImlzcyI6IjVkZDgzYmYwMGU0MjNkMTQ5OGRjYmFjYSIsImV4cCI6MTY0OTQzMzIzMiwiT3JnVW5pdElkIjoiNWZlMzc3Y2UwOWM1MGIyZDQwOGY2Y2YwIiwiUGF5bG9hZCI6eyJBQ1NVcmwiOiJodHRwczovL21lcmNoYW50YWNzc3RhZy5jYXJkaW5hbGNvbW1lcmNlLmNvbS9NZXJjaGFudEFDU1dlYi9wYXJlcS5qc3A_dmFhPWImZ29sZD1BQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUEiLCJQYXlsb2FkIjoiZU5wVlVjdHV3akFRdlBzckVKVjZhNXc0Q1ZDNldBcU5xbEtwbFBKUUg3ZmdyQ0EwTDV5a1FMKytkZ2pRM25abXZkNlpXWml2SmFJL1ExRko1UENNUlJHc3NCV0ZnL1lzbDdFejJ0aGZxOVY0WXIxdmt4L1BiSE9ZZUZQY2N2aEdXVVJaeWkzRE5CalFFeVRxQ3luV1FWcHlDTVIyT0JwengzUTdiaGRvQXdra0tFYyt0NWp0dUIyZ1IwUWdEUkxrZWJXTUkzRVRZcElCclJrQ0lxdlNVaDU0enpHQm5nQ0JTc1o4WFpaNW45TGRibWZnUGtqeUdBMlJKVUIxandDOVNKbFV1aXFVdzMwVThvVTlQQ3o5NlZPd0djdFBGcjRzL0ljUDhXWjFYdWZlQUtoK1FTQU1TdVRNWk14MHpGN0xjdnF1M1hlVjBab25FQ1JhQ0wrK3NqcjJuY3BBU1dzb0FybGU1aDJScFR0L0NlV25raEpUb1F3eFpmK01DT0ErejFKVWI5U2FjNjFzWE1UZlArcFVSYWtDYyszYkxtTzJqclhHOVhpa2ttR09kWnlQNnBpb25xSE4wV2h6WDFYOXUvc3ZkakduT0E9PSIsIlRyYW5zYWN0aW9uSWQiOiJTcHJsNElqM2tnZ05QMVhxbXpBMCJ9LCJPYmplY3RpZnlQYXlsb2FkIjp0cnVlLCJSZXR1cm5VcmwiOiJodHRwczovL3dlYi5lLnRlc3QuY29ubmVjdC5wYXltZW50c2Vuc2UuY2xvdWQvcGF5bWVudHMvRmp4TVAtdzZWU0JoVWhJOTItOGR4QUpjSjM4RFEzak1FUU1nbE9jU3FaYUZCY2wtQXAzVGJkak5SM1U3UEF3Z0F3WTZTaENLc25RVXByUlMyYWR6ZDZfQWhrOVNiUkFuVHZDVTZzX1RlTl9KU0NJUDRxTDRpV3BHb1o1RFpaV3B2aXJybVVxODlMbDFIc0hYQlUtVWlMMUdRdUZXL1RocmVlRFNlY3VyZTIwQ29tcGxldGUifQ.bJrA-EW3Z8ujPPGzdjkTYw8_gNj3EALFCWcNk7GwCB4"
                )
            }
        }
        supportFragmentManager
            .beginTransaction()
            .add(R.id.container, fragment)
            .commit()
    }

    override fun onBackPressed() {
        if (viewModel.canExit) super.onBackPressed()
    }
}