package tech.dojo.pay.sdk.card

import android.content.Intent
import android.os.Bundle
import androidx.activity.viewModels
import androidx.appcompat.app.AppCompatActivity
import tech.dojo.pay.sdk.R
import tech.dojo.pay.sdk.card.entities.DojoCardPaymentResult

internal class DojoCardPaymentActivity : AppCompatActivity() {

    private val viewModel: DojoCardPaymentViewModel by viewModels {
        DojoCardPaymentViewModelFactory(intent.extras)
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_dojo_card_payment)
        observeEvents()
    }

    private fun observeEvents() {
        viewModel.events.observe(this) { event ->
            when (event) {
                is DojoCardPaymentEvent.ReturnResult -> returnResult(event.result)
                is DojoCardPaymentEvent.Navigate3DS -> navigate3DS()
            }
        }
    }

    private fun returnResult(result: DojoCardPaymentResult) {
        val data = Intent()
        data.putExtra(DojoCardPaymentResultContract.KEY_RESULT, result)
        setResult(RESULT_OK, data)
        finish()
    }

    private fun navigate3DS() {
        supportFragmentManager
            .beginTransaction()
            .add(R.id.container, Dojo3DSFragment())
            .commit()
    }

    override fun onBackPressed() {
        if (viewModel.canExit) super.onBackPressed()
    }

    private fun observe3DSEvent() {
        viewModel.threeDsNavigationEvent.observe(this) {
            val fragment = Dojo3DSFragment().apply {
                arguments = Bundle().apply {
                    putString(Dojo3DSFragment.KEY_STEP_UP_URL, "https://centinelapistag.cardinalcommerce.com/V2/Cruise/StepUp")
                    putString(Dojo3DSFragment.KEY_MD, "6494143445096512304005")
                    putString(Dojo3DSFragment.KEY_JWT, "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI2YzI1MzQxOS01NDJjLTQ2NjctYTg4YS1lYTViN2FhNjMzOWMiLCJpYXQiOjE2NDk0MTQzNDQsImlzcyI6IjVkZDgzYmYwMGU0MjNkMTQ5OGRjYmFjYSIsImV4cCI6MTY0OTQxNzk0NCwiT3JnVW5pdElkIjoiNWZlMzc3Y2UwOWM1MGIyZDQwOGY2Y2YwIiwiUGF5bG9hZCI6eyJBQ1NVcmwiOiJodHRwczovL21lcmNoYW50YWNzc3RhZy5jYXJkaW5hbGNvbW1lcmNlLmNvbS9NZXJjaGFudEFDU1dlYi9wYXJlcS5qc3A_dmFhPWImZ29sZD1BQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUEiLCJQYXlsb2FkIjoiZU5wVlVjdE93ekFRdlBzcktwQzRFVHRPMGhkYlMzMVFLRkpSU1ZzTzNJS3pvb0c4NmlTay9EMTJtclp3MjVuZHRXZG1ZYk5UaUxNMXlrcWhnQ1VXUmZDQm5TZ2NYYW5wNEg2UkZCTVp4amJicnRqR3o5bVZnTlhZeDcyQWIxUkZsS1hDdHBqRmdaNGcwVThvdVF2U1VrQWc5NVBGczNDWjEvVjZRRnRJSUVHMW1BbWJPNjdYQlhwRUJOSWdRWkZYNzNFa2IwTk1NcUFOUTBCbVZWcXFIOUYzR2RBVElGQ3BXT3pLTWg5U1d0ZTFoWWNneVdPMFpKWUFOVDBDOUNKbFZabXEwQTRQVVNqazE5THp0M0VwMmRQbjIwTjlXTTVmWDVaemZ5MW40eEZRTTBFZ0RFb1VuSEhPWE5idjJHem9ESWJNQmRyd0JJTEVDQkUzMTNiWHVkTVphR2t0UlNBM240MlB5RGFkdjRUMlV5bUZxZFNHdUxaL1JnVHdrR2NwNmhtZDU3bldOaTdpcDQ4bVZWbnF3RHhuME9QY01iRTJ1Rm1QZERMY3RZLzdVUk1UTlR1MFBScHQ3NnVyZjNmL0JkT3ZweGc9IiwiVHJhbnNhY3Rpb25JZCI6InJDOUVJbXNCY2RsMTBVUDBUUnAwIn0sIk9iamVjdGlmeVBheWxvYWQiOnRydWUsIlJldHVyblVybCI6Imh0dHBzOi8vd2ViLmUudGVzdC5jb25uZWN0LnBheW1lbnRzZW5zZS5jbG91ZC9wYXltZW50cy9kdXhiVEk4dlVQTDFlc29zUjVKM0VvUnZXZ0gtVUtxZ0pMS3R6amg1cnpaZUlrVFVQQ0pVbkJJenhBVHMwVG8zNnJFVnZoNWttWDdxU1QySzRzU2lmbG1sTFpWLXVTWmM1VGh2Mjh4UHJRZkV2aERkWFZPWks4MHlMUVduWEphQkpMbHF4a3V5ejdBaVp6cEpVejJ1dE50SzBsSVUvVGhyZWVEU2VjdXJlMjBDb21wbGV0ZSJ9.ugXX0frg18GHEqvi3JuDonbdA8Yhrp9KmXVYypUmQTA")
                }
            }
            supportFragmentManager
                .beginTransaction()
                .add(R.id.container, fragment)
                .commit()
        }
    }

    override fun onBackPressed() {
        if (viewModel.canExit) super.onBackPressed()
    }
}